const workExperience = [
  {
    position: "Freelance Frontend/Mobile Developer",
    company: "Project: Pixie Trader — Cryptocurrency Trading Mobile App",
    location: "",
    period: "Jan 2026 - Jul 2026",
    responsibilities: [
      "Developed a cross-platform React Native application for crypto trading across multiple exchanges (CCXT-compatible) connected to a NestJS backend",
      "Integrated Socket.IO for real-time market data streaming, live ticker prices, and interactive OHLCV charts",
      "Built dynamic UI interfaces for automated trading bots (Static step-based, Grid, and EMA crossover strategies), multi-wallet management, and customizable market watchlists with sparkline charts",
      "Implemented adaptive layouts (Bottom Tabs for phones, Persistent Drawer for tablets) and complete multi-language support",
      "Leveraged AI coding assistants for rapid prototyping, complex UI component generation, and efficient logic debugging. Managed code repositories and task tracking via GitLab and Redmine",
    ],
    technologies: [
      "React Native",
      "Expo",
      "TypeScript",
      "Redux",
      "Socket.io",
      "AI Tools",
      "GitLab",
      "Redmine",
    ],
    achievements: [
      "Enhanced experience with mobile application development using React Native",
      "Experienced with AI coding assistants for rapid prototyping and efficient logic debugging",
      "Real time data streaming and interactive OHLCV charts",
    ],
  },
  {
    position: "Frontend Developer",
    company: "VietNam Blockchain Corporation",
    location: "Ho Chi Minh City, Vietnam",
    period: "Oct 2022 - Dec 2025",
    responsibilities: [
      "Developing and implementing UI functionalities for product traceability, e-commerce and water industry projects",
      "Built responsive layouts using Tailwind CSS and TypeScript, maintaining strict UI fidelity aligned with Figma/UI-UX designs",
      "Utilized Next.js (SSR/SSG) to optimize first-screen loading time, render performance, and SEO practices",
      "Worked with BE engineers on RESTful API integrations and security best practices",
      "Communicated directly with Business Analysts to translate business goals into technical requirements and clean system designs",
      "Partnered with QC/QA teams to investigate edge cases, perform root-cause troubleshooting, and resolve complex production bugs",
      "Integrated AI coding assistants (Claude Code) to streamline boilerplate creation, rapidly build  prototypes, and refactor complex logic"
    ],
    technologies: [
      "ReactJS",
      "TypeScript",
      "Tailwind CSS",
      "Material UI",
      "React Query",
      "Redux",
      "Redux Toolkit",
      "Next.js",
      "React Native",
      "AI Tools",
    ],
    achievements: [
      "Experienced with mobile application development using React Native",
      "Optimized website performance and SEO",
    ],
  },
  {
    position: "Junior Frontend Developer",
    company: "Positive Thinking Company",
    location: "Ho Chi Minh City, Vietnam",
    period: "Jun 2021 - Sep 2022",
    responsibilities: [
      "Implemented user interfaces and handled front-end issues",
      "Managed application state with Redux and handled form integration and asynchronous API processing via Formik and Axios",
      "Refactored existing modules to improve code maintainability, reusability, and overall user experience",
      "Authored comprehensive UI unit tests using Jest and React Testing Library to ensure high code reliability",
      "Worked in an Agile/Scrum environment, participating in daily standups and sprint planning with cross-functional teams, collaborating with QC and BE teams to debug and resolve complex frontend issues"
    ],
    technologies: [
      "ReactJS",
      "TypeScript",
      "Bootstrap",
      "Reactstrap",
      "Redux",
      "React Sweet State",
      "Formik",
      "Axios",
      "Jest",
      "React Testing Library",
    ],
    achievements: [
      "Enhanced programming skills, resulting in higher quality and more maintainable code",
      "Successfully organized workload and practiced effective self-management to deliver assignments on time",
    ],
  },
  {
    position: "ReactJS Intern",
    company: "PycoGroup",
    location: "Ho Chi Minh City, Vietnam",
    period: "Mar 2021 - May 2021",
    responsibilities: [
      "Participated in training sessions and contributed to the final internship project, HiClinic",
      "Developed application system for patient booking and admin management",
    ],
    technologies: [
      "ReactJS",
      "Hooks",
      "Bootstrap",
      "Reactstrap",
      "Formik",
      "Yup",
      "Axios",
      "Context API",
    ],
    achievements: [
      "Enhanced ReactJS programming knowledge through hands-on project experience",
      "Improved soft skills, including English proficiency and public speaking abilities",
    ],
  },
  {
    position: "Javascript Intern",
    company: "Alax Vietnam",
    location: "Ho Chi Minh City, Vietnam",
    period: "Jun 2019 - Aug 2019",
    responsibilities: [
      "Trained in Node.js, Git, and basics of ReactJS",
      "Built a functional live data widget with ReactJS to monitor CoinMarketCap website health status",
    ],
    technologies: ["JavaScript", "Node.js", "Git", "ReactJS"],
    achievements: [
      "Implemented source code management practices using Git",
      "Gained understanding of Agile working model",
    ],
  },
];

export default workExperience;
